### PR TITLE
Add basic Vale configuration

### LINKED ISSUE #1289: Check for links to `docs.opensafely.org` in PRs
Spotted in #1290. I've fixed these there, but there's nothing to stop anyone reintroducing them in future.

Contributors may not realise that the preferable approach is linking internally to the documentation, rather than the published version of that site, so that the URLs are to the correct version of the documentation wherever it is built and run. It does not help that the Markdown URL syntax is easy to get wrong when linking to files. 

We could probably use Vale or similar — see #643 — to check for this and suggest to someone making changes that they probably want a relative Markdown link.

### LINKED ISSUE #1291: Warn for the use of "here" in link text in PRs
Spotted in #1290. I've fixed these there, but there's nothing to stop anyone reintroducing them in future.

This is a smell: it's likely someone is using `[here](<URL>)`.

"here" alone in link text is almost always bad; and "here" in conjunction with other words is probably redundant.

Relates to #1289.

### PR DESCRIPTION
**Pull request by StevenMaude**
Fixes #1289.
Fixes #1291.
Relates to #519 and #643.

This adds a minimal Vale configuration as a trial.

With this change, adding rules can help us be more consistent across our documentation. These are not enforced anywhere, but can be checked optionally by one or more of:

* running Vale locally against the documentation source via `just lint-docs`
* installing Vale into editor/IDE for suggestions while editing
* running the `check_docs` workflow, included in this PR that allows you to list the suggestions for a branch

The rules may still need further refinement especially as they are regex-based, but they are not enforced anywhere.

Running Vale with these rules on the documentation source results in 0 suggestions, since these were fixed in #1304.

:warning: This PR *does not*:

* add some automated way of installing Vale locally; individuals must do that themselves.
* check the ehrQL documentation; that will need some thinking about integration, particularly because:
  * ehrQL documentation is pulled in separately from the ehrQL repository
  * a sizeable chunk of the ehrQL documentation is autogenerated from Python docstrings

### CODE REVIEW

**Comment by StevenMaude** [comment]
TODO:
- [ ] think about the Vale action is OK or we need something else here; the dependencies are well out-of-date: errata-ai/vale-action#104

**Comment by StevenMaude** [comment]
Example:

vale-with-opensafely-docs

**Comment by StevenMaude** [comment]
Even if we don't use the action, being able to quickly review text that may not fit with our house style (whatever that becomes) is useful.

**Comment by StevenMaude** [comment]
Looking through other style guides that Vale offers, here's a non-exhaustive list of potential useful ideas we could add rules for.

# Incomplete thoughts

* `TODO` or similar left in the text
  * https://github.com/errata-ai/proselint/blob/acedc7cb5400c65201ff06382ff0ce064bc338cb/proselint/Annotations.yml

# Helping the reader


* general consistency of word use and favouring simpler words/phrases
  * https://github.com/errata-ai/Google/blob/d31fa52ec19a6e2350100cc11d9653fc0e93f03d/Google/WordList.yml
  * https://github.com/errata-ai/Microsoft/blob/679b61f50b24f753a9bf7e31e1d30b6945c79190/Microsoft/ComplexWords.yml
  * https://github.com/errata-ai/Microsoft/blob/679b61f50b24f753a9bf7e31e1d30b6945c79190/Microsoft/Adverbs.yml
* favouring active voice
  * https://github.com/errata-ai/Google/blob/d31fa52ec19a6e2350100cc11d9653fc0e93f03d/Google/Passive.yml
  * https://github.com/errata-ai/Microsoft/blob/679b61f50b24f753a9bf7e31e1d30b6945c79190/Microsoft/Passive.yml
* encouraging shorter sentence and paragraph length 
  * https://github.com/errata-ai/IBM/blob/09be37d7b387b41158e1fb928f4c32424db9b7f8/IBM/SentenceLength.yml
* ensuring abbreviations are defined on first use
  * https://github.com/errata-ai/Google/blob/d31fa52ec19a6e2350100cc11d9653fc0e93f03d/Google/Acronyms.yml
* minimising use of parentheses
  * https://github.com/errata-ai/Google/blob/d31fa52ec19a6e2350100cc11d9653fc0e93f03d/Google/Parens.yml

# Formatting

* heading text formatting
  * https://github.com/errata-ai/Google/blob/d31fa52ec19a6e2350100cc11d9653fc0e93f03d/Google/HeadingPunctuation.yml
  * https://github.com/errata-ai/Microsoft/blob/679b61f50b24f753a9bf7e31e1d30b6945c79190/Microsoft/Headings.yml
* avoiding periods in abbreviations
  * https://github.com/errata-ai/Google/blob/d31fa52ec19a6e2350100cc11d9653fc0e93f03d/Google/Periods.yml

# General consistency

* deciding on contractions
  * https://github.com/errata-ai/Google/blob/d31fa52ec19a6e2350100cc11d9653fc0e93f03d/Google/Contractions.yml
  * https://github.com/errata-ai/Microsoft/blob/679b61f50b24f753a9bf7e31e1d30b6945c79190/Microsoft/Contractions.yml
* avoiding `e.g.` and `i.e.`
  * https://github.com/errata-ai/Google/blob/d31fa52ec19a6e2350100cc11d9653fc0e93f03d/Google/Latin.yml
* comma consistency
  * https://github.com/errata-ai/Google/blob/d31fa52ec19a6e2350100cc11d9653fc0e93f03d/Google/OxfordComma.yml
  * https://github.com/errata-ai/Microsoft/blob/679b61f50b24f753a9bf7e31e1d30b6945c79190/Microsoft/OxfordComma.yml
* spacing after periods
  * https://github.com/errata-ai/Microsoft/blob/679b61f50b24f753a9bf7e31e1d30b6945c79190/Microsoft/Spacing.yml

# Other checks

* consecutive word repetition (probably a mistake) 
  * https://github.com/errata-ai/write-good/blob/2d116619b7662d9d59201e8808254e715fc83cc8/write-good/Illusions.yml

**Comment by StevenMaude** [comment]
Checks need to be refined a little:

* checking for here in links captures things like "[where this…]"
* check for "OpenSAFELY" needs to be not checking in links, whether `< >` or `[ ]( )`

**Comment by StevenMaude** [comment]
We discussed this in our weekly team meeting, and it seems like not making checks mandatory is a good idea. But, even if solely included to:

* document a style
* as a tool for people more interested in editing the content

it's still useful.

**Review by inglesp — APPROVED** [review]
Thanks, all looks reasonable and useful -- and if we find it gives too many false positives we can easily remove.

Is there somewhere that this could be briefly documented?

**Comment by StevenMaude** [comment]
> Is there somewhere that this could be briefly documented?

I can add a note, maybe to the README. It's where we have the link checking information.

**Comment by StevenMaude** [comment]
I added some explanatory notes, so merging.

**Pull request merged**
