### PR TITLE
Remove non-Codespaces guidance from Getting Started tutorial

### LINKED ISSUE #1396: Consider only using Codespaces for Getting Started guide
There are enough new concepts and steps required, that facilitating a local installation when someone is first trying out OpenSAFELY is perhaps an extra step too far.

The branching also makes reading the document clunky because there are two paths for most of the steps.

By using only Codespaces, this would:

* make it clearer for the reader to know what they are doing, and give them only one set of instructions
* make it easier for the user to get to success in this guide — editing a study repository, pushing it to GitHub and seeing the tests pass — because Codespaces is less likely to give problems than installing software
* give the user a better idea of the steps needed for success, before they start trying to install the required software
* reduce the total length of the Getting Started source document
* allow us to add more screenshots along the way; it's not easy to do this right now because some of the instructions are shared for users running OpenSAFELY in a browser and locally 

The reader could be directed to another tutorial or explanation of the required software, and guidance for installation.

### PR DESCRIPTION
**Pull request by StevenMaude**
Fixes #1396.

Partly addresses opensafely-core/codespaces-initiative#30.

### CODE REVIEW

**Comment by StevenMaude** [comment]
Depends on #1478.

**Comment by StevenMaude** [comment]
In this PR, I am pulling out the non-Codespaces content from the Getting Started tutorial, and either:

* merging it with the duplicated content, if it is a duplicate of existing information
* storing it in the most relevant place, if it is not a duplicate of existing information

That's not to say that we should keep everything that's moved here, but it:

* cleans up the existing tutorial to streamline it to relevant information only
* highlights what has been moved out, giving us a way to decide to keep or delete

**Comment by StevenMaude** [comment]
Another improvement would be to split the tutorial into pages that represent each step, like the ehrQL tutorial. So instead of numbered sections in a single page, there would be one page for each section, and maybe an introductory page.

I'm not sure that's worth doing right now, as we may remove most or all of what we have in the near future.

**Comment by StevenMaude** [comment]
I also think that any newly added pages should probably be added to the table of contents too. As it's not yet decided what should be included, I haven't done so.

**Review by iaindillingham — APPROVED** [review]

**Pull request merged**
