### PR TITLE
Add rounding instructions to disclosure docs

### PR DESCRIPTION
**Pull request by LFISHER7**
This could be expanded on in the future, but provides at least some instruction for rounding.

### CODE REVIEW

**Comment by StevenMaude** [comment]
suggestion: Would it be useful to have a concrete example with fictitious data? This could show tables *before* and *after* the redaction and rounding process.

This might help illuminate the details, in case a reader either misinterprets the instructions or is otherwise unclear on the meaning.

It's possible to add [simple tables in the Markdown](https://squidfunk.github.io/mkdocs-material/reference/data-tables/) without too much work.

**Comment by StevenMaude** [comment]
Otherwise, the text looks fine. But better for someone who knows our disclosure controls well to approve it :mag:

**Comment by LFISHER7** [comment]
Thanks @StevenMaude , that's a good suggestion, I'll get something added

**Review by Jongmassey — APPROVED** [review]
Both the text and example are excellent, and I look forward to referring researchers to this in future!

**Pull request merged**
