### PR TITLE
Remove ONS CIS data

### PR DESCRIPTION
**Pull request by iaindillingham**

### CODE REVIEW

**Comment by Jongmassey** [comment]
The menu still contains a reference to the dataset

**Comment by iaindillingham** [comment]
> The menu still contains a reference to the dataset

Thanks, @Jongmassey. Removed.

**Review by Jongmassey — APPROVED** [review]
👍

**Comment by StevenMaude** [comment]
There's also:

* this include: https://github.com/opensafely/documentation/blob/655325811c3215e204b3166f13a2f320d89497f2/includes/onscis-warning-header.md
* this autogenerated documentation: https://github.com/opensafely/documentation/blob/655325811c3215e204b3166f13a2f320d89497f2/docs/study-def-variables.md?plain=1#L150-L158

**Comment by iaindillingham** [comment]
Thanks, @StevenMaude. Removed.

**Pull request merged**
